/**
 * Códigos de erro padronizados do sistema.
 * Use estes códigos no campo `error.code` da resposta HTTP.
 */
export enum ErrorCode {
  // Autenticação
  AUTH_REQUIRED = 'AUTH_REQUIRED',
  AUTH_INVALID_TOKEN = 'AUTH_INVALID_TOKEN',
  AUTH_EXPIRED_TOKEN = 'AUTH_EXPIRED_TOKEN',
  AUTH_INVALID_CREDENTIALS = 'AUTH_INVALID_CREDENTIALS',
  AUTH_USER_DISABLED = 'AUTH_USER_DISABLED',
  AUTH_USER_PENDING = 'AUTH_USER_PENDING',

  // Autorização
  FORBIDDEN = 'FORBIDDEN',
  INSUFFICIENT_PERMISSIONS = 'INSUFFICIENT_PERMISSIONS',
  TENANT_ACCESS_DENIED = 'TENANT_ACCESS_DENIED',

  // Validação
  VALIDATION_ERROR = 'VALIDATION_ERROR',
  INVALID_INPUT = 'INVALID_INPUT',

  // Recursos
  NOT_FOUND = 'NOT_FOUND',
  ALREADY_EXISTS = 'ALREADY_EXISTS',
  CONFLICT = 'CONFLICT',

  // Regras de negócio
  BUSINESS_RULE_VIOLATION = 'BUSINESS_RULE_VIOLATION',
  CLIENTE_BLOQUEADO_OMIE = 'CLIENTE_BLOQUEADO_OMIE',
  DESCONTO_ACIMA_TETO = 'DESCONTO_ACIMA_TETO',
  PEDIDO_JA_APROVADO = 'PEDIDO_JA_APROVADO',
  APROVACAO_PENDENTE = 'APROVACAO_PENDENTE',

  // Integrações
  INTEGRATION_ERROR = 'INTEGRATION_ERROR',
  OMIE_ERROR = 'OMIE_ERROR',
  WHATSAPP_ERROR = 'WHATSAPP_ERROR',
  MARKETPLACE_ERROR = 'MARKETPLACE_ERROR',
  AI_ERROR = 'AI_ERROR',

  // Fluxos de Automação
  FLUXO_INVALIDO = 'FLUXO_INVALIDO',
  FLUXO_JA_ATIVO = 'FLUXO_JA_ATIVO',
  FLUXO_NAO_PODE_ATIVAR = 'FLUXO_NAO_PODE_ATIVAR',

  // Campanhas
  CAMPANHA_SEM_DESTINATARIOS = 'CAMPANHA_SEM_DESTINATARIOS',
  CAMPANHA_NAO_PODE_DISPARAR = 'CAMPANHA_NAO_PODE_DISPARAR',

  // Infraestrutura
  DATABASE_ERROR = 'DATABASE_ERROR',
  RATE_LIMIT_EXCEEDED = 'RATE_LIMIT_EXCEEDED',
  INTERNAL_ERROR = 'INTERNAL_ERROR',
  SERVICE_UNAVAILABLE = 'SERVICE_UNAVAILABLE',
}
